### ISSUE TITLE
Add a more advanced Django App to Recipes and Tips Section

### ISSUE THREAD

**Issue by ProfessorLogout** [caprover/caprover-website#11]
Hello,

I have recently open-sourced a Django "boilerplate" [project](https://gitlab.com/kamneros/caprover-django) for simple deployment on CapRover with PostgreSQL.
Would it be OK to add e excerpt and link to the project in the Recipes And Tips Section on a page along the lines of "Advanced Django App".

Greetings
Marco

**Comment by githubsaturn** [comment]
Sure - feel free to add it at the bottom of this page:
https://github.com/caprover/caprover-website/blob/master/docs/sample-apps.md

Create a category called "Community Apps", add a bit of excerpt and add your link :+1:
