### ISSUE TITLE
Remove www subdomain from github about

### ISSUE THREAD

**Issue by TreyWW** [caprover/caprover-website#123]
![image](https://github.com/caprover/caprover-website/assets/73353716/fc5f3996-527b-4d43-982d-3648da9f5ff9)

WWW Subdomain is invalid 
![image](https://github.com/caprover/caprover-website/assets/73353716/e75bbfef-15c3-46cc-be99-e6ecfd48ec10)

I suggest removing subdomain fully

**Comment by githubsaturn** [comment]
Thanks for the report. it's fixed now!

https://www.caprover.com now redirects to https://caprover.com
