### ISSUE TITLE
Domain and DNS link in Get Started section goes nowhere

### ISSUE THREAD

**Issue by GamerKingFaiz** [caprover/caprover-website#133]
The nonexistent link can be found on this line here: https://github.com/caprover/caprover-website/blob/master/docs/get-started.md?plain=1#L27

I would love to know what this would've linked to or where to get a $2/year domain. :)

**Comment by githubsaturn** [comment]
That's an internal link that was supposed to take you further down in the set up. Not a referral link :)

But if you really want cheap domains, here is a link for you!

https://www.namecheap.com/domains/registration/results/?domain=gsfdgsdgsdgsfg
![image](https://github.com/caprover/caprover-website/assets/10582082/08892d06-4cc5-4a95-a695-c91eda8508b2)

**Comment by githubsaturn** [comment]
The original link was to this section which then got moved around:
https://github.com/caprover/caprover/tree/a661d32566b9a29abb3c545c9ff9b765d54add60?tab=readme-ov-file#setup-domain-and-dns

In the new docs, this link doesn't make any sense, I'll remove it.

**Comment by githubsaturn** [comment]
Here is another link: https://www.reddit.com/r/selfhosted/comments/sp8etq/comment/hwdgztx/?utm_source=reddit&utm_medium=web2x&context=3
