### ISSUE TITLE
Step 1: CapRover Installation

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover-website#31]
[Step 1 (CapRover Installation)](https://caprover.com/docs/get-started.html#step-1-caprover-installation) says that we should run the following:

    docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover

For some time now, I've just been running:

    docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock caprover/caprover

What is the effect of the extra `/captain:/captain` that I haven't been using?

**Comment by githubsaturn** [comment]
It just ensures that `/captain` directory exists on your host machine. Previously we used to have `mkdir -p /captain &&...`, that is now replaced by `/captain:/captain` which has the same effect.
On some systems, if the directory isn't present before installation, docker cannot bind the service.

**Comment by drmrbrewer** [comment]
Ha, OK.  Indeed my full "one-line install" command has a bit before what I said, which is indeed to create `/captain`:

    mkdir /captain && docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock caprover/caprover
