### ISSUE TITLE
wrong url for the Docs in the footer when you're already in the doc

### ISSUE THREAD

**Issue by JOduMonT** [caprover/caprover-website#96]
Sadly I don't know docusaurus, but this link doesn't work properly https://github.com/caprover/caprover-website/blob/master/website/core/Footer.js#L38

### How to reproduce
1. [goto the doc](https://caprover.com/docs/get-started.html)
2. scroll down
3. click on [Getting Started](https://caprover.com/docs/en/get-started.html)

**Comment by githubsaturn** [comment]
Fixed here: https://github.com/caprover/caprover-website/commit/29994bcd6811e09388ee647452d8651762a84531
